GET http://localhost:8081/api/ai/chat1?memoryId=1&message=小王是谁

###
GET http://localhost:8081/api/ai/chat1?memoryId=1&message=那你帮我查询一下aaa.aaa这张表里面的内容

###
GET http://localhost:8081/api/ai/chat1?memoryId=1&message=那你帮我查询一下aaa.aaa这张表里面的内容，并统计一下里面一共有多少条数据，name不相同的有多少条，并分别给出对应的数据

###
GET http://localhost:8081/api/ai/chat1?memoryId=1&message=你好，我是小王,帮我把你好世界翻译成英文

###
GET http://localhost:8081/api/ai/chat1?memoryId=1&message=我是谁
